=== usdot-fhwa-stol/v2x-ros-driver/v2x_ros_driver/etc/wave_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Wave Config Schema",
  "description": "A simple schema to describe Wave messages",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "description": "message type - abbreviated name",
        "type": "string"
      },
      "psid": {
        "description": "psid assigned to message type in 2-byte Hex ie 8003 or 0020",
        "type": "string"
      },
      "dsrc_id": {
        "description": "J2735 wave id assigned to message type in decimal",
        "type": "string"
      },
      "channel": {
        "description": "Wave radio channel assigned to message type in decimal",
        "type": "string"
      },
      "priority": {
        "description": "WSM Priority to use assigned to message type in decimal",
        "type": "string"
      }
    },
    "required":["name","psid","dsrc_id","channel","priority"]
  }
}

=== usdot-fhwa-stol/v2x-ros-driver/dsrc_driver/config/wave.json
[
  {
    "name" : "BSM",
    "psid" : "0020",
    "dsrc_id" : "20",
    "channel" : "183",
    "priority" :  "6"
  },
  {
    "name" : "TIM",
    "psid" : "0083",
    "dsrc_id" : "31",
    "channel" : "CCH",
    "priority" : "3"
  },
  {
    "name" : "MAP",
    "psid" : "0082",
    "dsrc_id" : "18",
    "channel" : "183",
    "priority" : "3"
  },
  {
    "name" : "SPAT",
    "psid" : "0082",
    "dsrc_id" : "19",
    "channel" : "183",
    "priority" : "3"
  },
  {
    "name" : "MobilityRequest",
    "psid" : "BFEE",
    "dsrc_id" : "240",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "MobilityResponse",
    "psid" : "BFEE",
    "dsrc_id" : "241",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "MobilityOperation",
    "psid" : "BFEE",
    "dsrc_id" : "243",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "MobilityPath",
    "psid" : "BFEE",
    "dsrc_id" : "242",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "TrafficControlRequest",
    "psid" : "8003",
    "dsrc_id" : "244",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "PSM",
    "psid" : "0027",
    "dsrc_id" : "32",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "TrafficControlMessage",
    "psid" : "8003",
    "dsrc_id" : "245",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "EmergencyVehicleResponse",
    "psid" : "8005",
    "dsrc_id" : "246",
    "channel" : "183",
    "priority" : "6"
  },
  {
    "name" : "EmergencyVehicleAck",
    "psid" : "8005",
    "dsrc_id" : "247",
    "channel" : "183",
    "priority" : "6"
  }
]
